services:
  api:
    build: ./api
    container_name: motocare-api
    ports:
      - '3001:3001'
    volumes:
      - ./api/data:/app/data
    environment:
      - DB_PATH=./data/motocare.sqlite

  web:
    build: ./web
    container_name: motocare-web
    ports:
      - '4173:4173'
    depends_on:
      - api
